"""Regenerate mcp_server/_fonts.py — a subsetted, base64-embedded Geist Sans.

The widgets render in a sandboxed iframe with no access to the app's font
pipeline, so we embed Geist directly (subsetted to the glyphs the widgets use)
to match the storefront typography while staying self-contained.

Usage (from repo root, with the mcp_server venv active and deps installed):
    pip install fonttools brotli
    python mcp_server/scripts/subset_fonts.py

Requires node_modules/geist (i.e. run `npm install` first).
"""
import base64
import io
import os

from fontTools import subset
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "node_modules", "geist", "dist", "fonts", "geist-sans")
OUT = os.path.join(HERE, "..", "_fonts.py")

# Latin basic + Latin-1 + common punctuation (– — ' ' " " …) + bullet + π (Box #π).
UNICODES = "U+0020-007E,U+00A0-00FF,U+2010-2027,U+2032-2033,U+20AC,U+2122,U+03C0,U+2219,U+00B7"

FACES = [
    ("Geist-Regular.woff2", 400, "normal"),
    ("Geist-Medium.woff2", 500, "normal"),
    ("Geist-SemiBold.woff2", 600, "normal"),
    ("Geist-Italic.woff2", 400, "italic"),
]


def subset_b64(path: str) -> str:
    font = TTFont(path)
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.desubroutinize = True
    opts.layout_features = ["kern", "liga", "calt", "tnum"]
    opts.name_IDs = []
    opts.notdef_outline = True
    ss = subset.Subsetter(options=opts)
    ss.populate(unicodes=subset.parse_unicodes(UNICODES))
    ss.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return base64.b64encode(buf.getvalue()).decode()


def main() -> None:
    blocks = []
    for fn, wght, style in FACES:
        b64 = subset_b64(os.path.join(SRC, fn))
        blocks.append(
            "@font-face{font-family:'Geist';font-style:%s;font-weight:%d;font-display:swap;"
            "src:url(data:font/woff2;base64,%s) format('woff2')}" % (style, wght, b64)
        )
    css = "".join(blocks)
    with open(OUT, "w") as f:
        f.write('"""Embedded, subsetted Geist Sans (@font-face, base64 woff2) for the widgets.\n')
        f.write('Generated by scripts/subset_fonts.py from node_modules/geist — do not hand-edit."""\n\n')
        f.write("FONT_FACE_CSS = " + repr(css) + "\n")
    print(f"Wrote {OUT} ({os.path.getsize(OUT) / 1024:.1f}KB)")


if __name__ == "__main__":
    main()
